name: 'Falco'
description: 'Falco Fastly VCL parser'
inputs:
  subcommand:
    description: 'Falco subcommand'
    required: true
    default: 'lint'
  target:
    description: 'File path to VCL'
    required: true
  options:
    description: 'Optional flags'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subcommand }}
    - ${{ inputs.options }}
    - ${{ inputs.target }}
