name: Test run for Falco GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Run Falco on valid ACL
        uses: ./
        with:
          subcommand: lint
          target: test/acl/valid.acl

      - name: Run Falco on valid ACL with verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -v
          target: test/acl/valid.acl

      - name: Run Falco on valid ACL with most verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -vv
          target: test/acl/valid.acl

      - name: Run Falco on ACL with invalid IP
        id: acl_invalid_ip
        uses: ./
        with:
          subcommand: lint
          target: test/acl/invalid_ip.acl

      - name: Run Falco on ACL with invalid IP range
        id: acl_invalid_ip_range
        if: ${{ failure() && steps.acl_invalid_ip.conclusion == 'failure' }}
        uses: ./
        with:
          subcommand: lint
          target: test/acl/invalid_range.acl

      - name: Consider complete
        if: ${{ failure() && steps.acl_invalid_ip_range.conclusion == 'failure' }}
        run: exit 0

      #- name: Run Falco on ACL with invalid syntax
        #uses: ./
        #with:
          #subcommand: lint
          #target: test/acl/invalid_syntax.acl
