name: Test run for Falco GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Falco on valid ACL
        uses: ./
        with:
          subcommand: lint
          target: test/acl/valid.acl

      - name: Run Falco on valid ACL with verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -v
          target: test/acl/valid.acl

      - name: Run Falco on valid ACL with most verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -vv
          target: test/acl/valid.acl

      #- name: Run Falco on ACL with invalid IP
        #uses: ./
        #with:
          #subcommand: lint
          #target: test/acl/invalid_ip.acl

      #- name: Run Falco on ACL with invalid IP range
        #uses: ./
        #with:
          #subcommand: lint
          #target: test/acl/invalid_range.acl

      #- name: Run Falco on ACL with invalid syntax
        #uses: ./
        #with:
          #subcommand: lint
          #target: test/acl/invalid_syntax.acl
  vcl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Falco on valid VCL
        uses: ./
        with:
          subcommand: lint
          target: test/vcl/valid.vcl

      - name: Run Falco on valid VCL with verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -v
          target: test/vcl/valid.vcl

      - name: Run Falco on valid VCL with most verbosity
        uses: ./
        with:
          subcommand: lint
          verbosity: -vv
          target: test/vcl/valid.vcl

      - name: Run Falco on valid VCL with include
        uses: ./
        with:
          subcommand: lint
          verbosity: -vv
          include: test/vcl/blocked_urls.vcl
          target: test/vcl/valid_with_include.vcl

      #- name: Run Falco on invalid VCL
        #uses: ./
        #with:
          #subcommand: lint
          #target: test/vcl/invalid_syntax.acl
