name: Test run for Falco GitHub Action

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Run Falco on valid ACL
        uses: ./
        with:
          subcommand: lint
          target: test/acl/valid.acl

      - name: Run Falco on ACL with invalid IP
        uses: ./
        with:
          subcommand: lint
          target: test/acl/invalid_ip.acl

      - name: Run Falco on ACL with invalid IP range
        uses: ./
        with:
          subcommand: lint
          target: test/acl/invalid_range.acl

      - name: Run Falco on ACL with invalid syntax
        uses: ./
        with:
          subcommand: lint
          target: test/acl/invalid_syntax.acl
